### ISSUE TITLE
Question about data retention

### ISSUE THREAD

**Issue by Lars-** [rijdendetreinen/gotrain#26]
Hi,

I love what you did with this data and I am planning to use it in our product. Quick question: how long will data be stored? I am planning to run this on a very low end server with 512MB RAM. Is there a way to limit the maximum memory usage or is this already managed withing the package?

**Comment by geertw** [comment]
Unfortunately not, as you'll ideally kepp all incoming data until the train has gone. Data about a train service is sent out approximately 5 days before departure and is kept until the train is gone (so 5 days in total). Typical memory usage is around 3600 MB virtual, ~ 780 MB resident memory. A server with only 512 MB would be a bit too scarce on memory.

**Comment by Lars-** [comment]
Thank you for the clear answer. A follow up question in that case: why can I query departures from yesterday? If they are deleted after departure, I should not be able to query them, right?
